#Create container for AEGeAn (https://aegean.readthedocs.io/en/stable/install.html) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git libcairo2-dev libpango1.0-dev

WORKDIR /opt

# Download, compile, and install the GenomeTools package
#RUN curl -O http://genometools.org/pub/genometools-1.5.8.tar.gz \
#  && tar xzf genometools-1.5.8.tar.gz \
#  && cd genometools-1.5.8 \
#  && make \
#  && make install \
#  && cd ..

ENV PATH /opt:$PATH
#
#
