#Create container for FLO (https://github.com/wurmlab/flo) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y ruby-full wget
RUN gem install bio

WORKDIR /opt
RUN wget -c https://github.com/yeban/flo/archive/master.tar.gz -O flo.tar.gz \
  && tar xvf flo.tar.gz \
  && mv flo-master flo \
  && rm flo.tar.gz \
  && flo/scripts/install.sh \



ENV PATH /opt/flo:$PATH
