#Create container for SparseAssembly (https://github.com/yechengxi/SparseAssembler) & DBG2OLC (https://github.com/yechengxi/DBG2OLC) to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget

WORKDIR /opt

git clone https://github.com/yechengxi/SparseAssembler
git clone https://github.com/yechengxi/DBG2OLC

#cd maker/src/
#perl Build.PL


#./Build status

#./Build installdeps
#./Build installexes
#./Build install
