#Create container for MitoGeneExtractor https://github.com/cmayer/MitoGeneExtractor
# ---- Build & runtime image with micromamba ----
FROM mambaorg/micromamba:1.5.8


# File Author / Maintainer
MAINTAINER Jason Selwyn "jason.selwyn@tamucc.edu"


# System build deps for MitoGeneExtractor (C++/make) + zlib for gz FASTQ
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential git zlib1g-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Create env with exonerate from Bioconda (channels: conda-forge > bioconda)
ARG ENV_NAME=mge
RUN micromamba create -y -n ${ENV_NAME} -c conda-forge -c bioconda \
      exonerate && \
    micromamba clean -a -y
ENV PATH=/opt/conda/envs/${ENV_NAME}/bin:$PATH

# Build MitoGeneExtractor and install the binary into the env
#WORKDIR /opt
#RUN git clone https://github.com/cmayer/MitoGeneExtractor.git && \
#    cd MitoGeneExtractor && \
#    make -j"$(nproc)" && \
#    install -m 0755 MitoGeneExtractor /opt/conda/envs/${ENV_NAME}/bin/ && \
#    rm -rf /opt/MitoGeneExtractor

# (Optional) default working dir for data
#WORKDIR /work
