############################################################
# Dockerfile to build Juicer container image
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Neva C. Durand

# Update the repository sources list
# Install base packages: java, git, wget
RUN apt-get update && apt-get install -y \
    default-jdk \
    gawk \
    gcc \
    git \
    libz-dev \
    locales \
    make \
    unzip \
    bzip2 \
    libbz2-dev \
&& rm -rf /var/lib/apt/lists/*

# GAWK has the 'and' function, needed for chimeric_blacklist
RUN echo 'alias awk=gawk' >> ~/.bashrc

# Need to be sure we have this for stats
RUN locale-gen en_US.UTF-8

WORKDIR /opt/

# Install BWA
RUN git clone https://github.com/lh3/bwa.git
RUN cd bwa && make

# Install Samtools
ADD https://github.com/samtools/samtools/releases/download/1.19/samtools-1.19.tar.bz2 .
RUN bunzip2 samtools-*.tar.bz2
RUN tar xf samtools-*.tar
RUN rm -rf samtools-*.tar
RUN cd samtools-* && ./configure --without-curses --disable-bz2 --disable-lzma && make && make install

# Install Juicer
ADD https://github.com/theaidenlab/juicer/archive/1.6.2.zip .
RUN unzip 1.6.2.zip
RUN cd juicer-1.6.2 && chmod +x CPU/* CPU/common/*

# Install Juicer tools
ADD https://s3.amazonaws.com/hicfiles.tc4ga.com/public/juicer/juicer_tools_1.22.01.jar /opt/juicer-1.22.01/CPU/common
#RUN ln -s /opt/juicer-1.6.2/CPU/common/juicer_tools.1.7.6_jcuda.0.8.jar /opt/juicer-1.6.2/CPU/common/juicer_tools.jar
#RUN ln -s juicer-1.6.2/CPU scripts

# Version number contained in image
#ADD VERSION .

# For sorting, LC_ALL is C
#ENV LC_ALL C
#ENV PATH=/opt:/opt/scripts:/opt/scripts/common:$PATH

#ENTRYPOINT ["juicer.sh", "-D", "/opt"]
#CMD ["-h"]







#https://github.com/theaidenlab/Juicer-Docker/issues/2

# Add executability to juicer tools file
#RUN chmod 777 /opt/juicer-1.6.2/CPU/common/juicer_tools.1.7.6_jcuda.0.8.jar

# Remove entrypoint
#ENTRYPOINT []
