#Create container for spades https://github.com/ablab/spades to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make wget cmake zlib-devel bzip2-devel

WORKDIR /opt

# Download the executable for the latest release.

RUN wget http://cab.spbu.ru/files/release3.15.4/SPAdes-3.15.4.tar.gz
RUN tar -xzf SPAdes-3.15.4.tar.gz
RUN rm /opt/SPAdes-3.15.4.tar.gz
WORKDIR /opt/SPAdes-3.15.4

RUN ./spades_compile.sh

ENV PATH /opt/SPAdes-3.15.4/bin:$PATH
