FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf install -y gcc make git wget python3 zip
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt

RUN git clone https://github.com/rajewsky-lab/mirdeep2.git

WORKDIR /opt/mirdeep2

RUN perl install.pl
RUN /bin/bash -c "source ~/.bashrc" && perl install.pl

ENV PATH /opt/mirdeep2/bin:$PATH
ENV PERL5LIB /opt/mirdeep2/lib/perl5
