#Create container for MEC https://github.com/bioinfomaticsCSU/MEC to run on NEU Discovery
FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget perl python2-devel python2-pip bzip2-devel
RUN dnf config-manager --set-enabled powertools
RUN pip2 install Cython
RUN pip2 install pysam

RUN ln -s /bin/python2 /bin/python

WORKDIR /opt

#Install HTSlib
RUN git clone https://github.com/samtools/htslib \
  && cd htslib \
  && git submodule update --init --recursive \
  && autoreconf -i \
  && ./configure \
  && make \
  && make install

#Install SAMTOOLS
RUN git clone https://github.com/samtools/samtools \
  && cd samtools \
  && autoheader \
  && autoconf -Wno-syntax \
  && ./configure --without-curses \
  && make \
  && make install

#Install bowtie2
RUN wget -O bowtie2.zip https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.4.5/bowtie2-2.4.5-source.zip/download \
  && unzip bowtie2.zip \
  && rm -rf bowtie2.zip \
  && mv bowtie* bowtie2 \
  && cd bowtie2 \
  && make
ENV PATH /opt/bowtie2:$PATH

#Install MEC
RUN git clone https://github.com/bioinfomaticsCSU/MEC
ENV PATH /opt/MEC/src:$PATH
