#Create container for Beta-PSMC (https://github.com/ChenHuaLab/Beta-PSMC) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git cmake

WORKDIR /opt

#RUN git clone https://github.com/lorrainea/mars && \
#  cd mars && \
#  ./pre-install.sh && \
#  make -f Makefile

#ENV PATH=/opt/mars/:$PATH
