#Create container for SparseAssembly (https://github.com/yechengxi/SparseAssembler) & DBG2OLC (https://github.com/yechengxi/DBG2OLC) to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget

WORKDIR /opt

RUN git clone https://github.com/yechengxi/DBG2OLC
RUN mv DBG2OLC tmp
RUN mv tmp/compiled/* ./
RUN mv tmp/utility/* ./
RUN rm -rf tmp

RUN git clone https://github.com/mchaisso/blasr
WORKDIR /opt/blasr
RUN make
RUN ln -s /opt/blasr/alignment/bin/blasrmc /opt/blasr/alignment/bin/blasr

ENV PATH /opt/blasr/alignment/bin:/opt:$PATH
