#Create container for LSD2 (https://github.com/tothuhien/lsd2) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git python2
RUN ln -s /usr/bin/python2 /usr/bin/python

WORKDIR /opt

RUN git clone https://github.com/genomeannotation/GAG

ENV PATH /opt/GAG:$PATH
