#Create container for Maker (https://github.com/Yandell-Lab/maker) to run on NEU Discovery
#Modified from: https://github.com/chrishah/maker-docker

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

#RepeatMasker Library = default curated - Dfam

#https://github.com/chrishah/maker-docker/blob/master/ubuntu-basic/Dockerfile
RUN apt-get update --fix-missing
RUN apt-get install -y build-essential vim git wget unzip language-pack-en rsync libcurl4 zlib1g-dev libpq-dev mpich cpio

RUN apt-get install -y perl cpanminus
RUN apt-get install -y python3 python3-pip
RUN pip install h5py
RUN apt-get install -y exonerate hmmer ncbi-blast+
RUN apt-get install -y augustus augustus-data augustus-doc libyaml-perl

#Set language
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

#Install required PERL modules
RUN cpanm YAML && \
        cpanm Hash::Merge && \
        cpanm Logger::Simple && \
        cpanm Parallel::ForkManager && \
        cpanm Text::Soundex && \
        cpanm File::Which && \
        cpanm Devel::Size && \
	      cpanm MCE::Mutex && \
        cpanm forks && \
        cpanm forks::shared && \
        cpanm File::Which && \
        cpanm Perl::Unsafe::Signals && \
        cpanm Bit::Vector && \
        cpanm Inline::C && \
        cpanm IO::All && \
        cpanm IO::Prompt && \
        cpanm BioPerl && \
        cpanm DBD::SQLite && \
        cpanm DBD::Pg && \
        cpanm Parallel::ForkManager && \
        cpanm Thread::Queue && \
        cpanm threads && \
        cpanm Math::Utils

#Add blast executables to location expected by RepeatModeler
RUN for f in $(find /usr/bin/ -name '*blast*'); do ln -s $f /usr/local/bin/; done
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/dustmasker /usr/local/bin/dustmasker

#https://github.com/chrishah/maker-docker/blob/master/ab-initio/Dockerfile
# install SNAP
WORKDIR /usr/src
RUN git clone --recursive https://github.com/KorfLab/SNAP.git \
  && cd /usr/src/SNAP \
  && make \
  && cd /usr/src
ENV ZOE="/usr/src/SNAP/Zoe"

#Download blat
WORKDIR /usr/bin
RUN rsync -aP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/blat/blat /usr/bin/
ENV PATH="/usr/src/SNAP:/usr/share/augustus/scripts:${PATH}"

#GeneMark
RUN mkdir /usr/local/Genemark
WORKDIR /usr/local/Genemark
ADD gmes_linux_64_4.tar.gz /usr/local/Genemark
ADD gm_key_64.gz /usr/local/Genemark
RUN cp -r gmes_linux_64_4/* ./
RUN rm -rf gmes_linux_64_4
RUN cp gm_key ~/.gm_key
ENV PATH="/usr/local/Genemark:${PATH}"

#https://github.com/chrishah/maker-docker/blob/master/repeatmasker/Dockerfile
#install Repeatmasker (much of this was taken and slighly modified from robsyme/repeatmasker-onbuild)
# Install TRF - Tandem Repeat Finder (for RepeatScout)
WORKDIR /usr/local
RUN cd bin && \
  wget http://tandem.bu.edu/trf/downloads/trf407b.linux64 && \
  mv trf*.linux64 trf && \
  chmod +x trf

# Install nseg (for RepeatScout)
WORKDIR /usr/local
RUN mkdir nseg && \
    cd nseg && \
    wget ftp://ftp.ncbi.nih.gov/pub/seg/nseg/* && \
    make && \
    mv nseg ../bin && \
    mv nmerge ../bin
