#Create container for matemaker https://github.com/josephryan/matemaker to run on NEU Discovery
FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git perl

RUN dnf config-manager --set-enabled powertools

WORKDIR /opt

RUN git clone https://github.com/josephryan/JFR-PerlModules
WORKDIR /opt/JFR-PerlModules
RUN perl Makefile.PL
RUN make
RUN make test
RUN make install

WORKDIR /opt

RUN git clone https://github.com/josephryan/matemaker
WORKDIR /opt/matemaker
RUN perl Makefile.PL
RUN make
RUN make install

RUN sed -i "1s/.*/\#\!\/usr\/bin\/perl/" matemaker

ENV PATH /opt/matemaker:$PATH
#matemaker --assembly=example/Hsap.chr22.subopt.fa --insertsize=2000 --out=chr22.2000
