#Create container for ngsLD https://github.com/fgvieira/ngsLD to run on NEU Discovery
FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

#RUN apt-get update --fix-missing
#RUN apt-get install -y build-essential vim git wget unzip language-pack-en rsync libcurl4 zlib1g-dev libpq-dev mpich cpio
#
#RUN apt-get install -y perl cpanminus
#RUN apt-get install -y python3 python3-pip


#RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
#RUN dnf -y distro-sync
#RUN dnf -y makecache
#RUN dnf -y groupinstall "Development Tools"
#RUN dnf install -y gcc make git perl gsl cpanminus python3 python3-pip

#RUN cpanm Getopt::Long && \
#       cpanm Graph::Easy && \
#       cpanm Math::BigFloat && \
#       cpanm IO::Zlib

#RUN pip3 install pandas
#dnf install python3-graph-tool-devel
