#Create container for shasta https://github.com/chanzuckerberg/shasta to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git

WORKDIR /opt

RUN git clone https://github.com/chanzuckerberg/shasta.git

#WORKDIR /opt/wtdbg2

#RUN make

#ENV PATH /opt/wtdbg2:$PATH
