FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget python3 zip perl
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt

RUN git clone https://github.com/rajewsky-lab/mirdeep2.git

WORKDIR /opt/mirdeep2

RUN perl install.pl
RUN /bin/bash -c "source ~/.bashrc"
RUN perl install.pl


#echo 'export PATH=$PATH:/opt/mirdeep2/src' >> ~/.bashrc
#echo 'export PATH=$PATH:/opt/mirdeep2/essentials/bowtie-1.1.1' >> ~/.bashrc
#echo 'export PATH=$PATH:/opt/mirdeep2/essentials/ViennaRNA-1.8.4/install_dir/bin' >> ~/.bashrc
#echo 'export PATH=$PATH:/opt/mirdeep2/essentials/randfold-2.0' >> ~/.bashrc
#echo 'export PERL5LIB=PERL5LIB:/opt/mirdeep2/lib/perl5' >> ~/.bashrc


#ENV PATH /opt/mirdeep2/bin:$PATH
#ENV PERL5LIB /opt/mirdeep2/lib/perl5
