#Create container for Beta-PSMC (https://github.com/ChenHuaLab/Beta-PSMC) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git cmake zlib1g-dev

WORKDIR /opt

RUN git clone https://github.com/ChenHuaLab/Beta-PSMC && \
  cd Beta-PSMC && \
  make

ENV PATH=/opt/Beta-PSMC/:$PATH
