#Create container for DASTool (https://github.com/cmks/DAS_Tool) to run on NEU Discovery

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Jason Selwyn

ENV htslib_version 1.15
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8


WORKDIR /tmp
RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	apt-utils time curl gnupg gcc g++ make autoconf && \
	apt-get clean && apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	git zlib1g-dev bzip2 libbz2-dev liblzma-dev && \
	apt-get clean && apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

## Install HTSlib
RUN curl -SL https://github.com/samtools/bcftools/releases/download/${htslib_version}/bcftools-${htslib_version}.tar.bz2 \
    > bcftools-${htslib_version}.tar.bz2 && \
    tar -xjvf bcftools-${htslib_version}.tar.bz2 && \
    rm -rf bcftools-${htslib_version}.tar.bz2 && \
    mv /tmp/bcftools-${htslib_version} /tmp/bcftools && \
    cd /tmp/bcftools && \
    ./configure && \
    make && \
    make install && \
    rm -rf bcftools-${htslib_version}.tar.bz2

## Install Boost
RUN curl -SL https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.bz2 \
    > boost.tar.bz2 && \
    tar -xjvf boost.tar.bz2 && \
    rm -rf boost.tar.bz2 && \
    mv boost* boost && \
    cd boost && \
    ./bootstrap.sh --with-libraries=iostreams,program_options --prefix=../boost && \
    ./b2 install && \
    cd ../boost


#
#echo amd64 > /var/lib/dpkg/arch
#echo i386 >> /var/lib/dpkg/arch
#apt-get update
#apt-get install plocate

#locate -b '\libz.so'
#locate -b '\libbz2.so'
#locate -b '\liblzma.so'
#locate -b '\libm.so'
#locate -b '\libpthread.so'
#locate -b '\libcurl.so'





## Install ShapeIT
RUN git clone --recurse-submodules https://github.com/odelaneau/shapeit5.git && \
  cd shapeit5

  curl https://github.com/odelaneau/shapeit5/releases/download/v5.1.1/ligate_static

#
common/makefile_common.mk

HTSSRC=/usr/local
HTSLIB_INC=$(HTSSRC)/include/htslib
HTSLIB_LIB=$(HTSSRC)/lib/libhts.a
BOOST_INC=/usr/include
BOOST_LIB_IO=$(shell whereis libboost_iostreams | grep -o '\S*\.a\b')
BOOST_LIB_PO=$(shell whereis libboost_program_options | grep -o '\S*\.a\b')

cd phase_common && \
  make

cd phase_rare && \
  make

cd switch && \
  make

cd ligate && \
  make

cd simulate && \
  make

cd xcftools && \
  make
