#Create container for BLCA (https://github.com/qunfengdong/BLCA) to run on NEU Discovery

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Jason Selwyn

# Update the repository sources list
# Install base packages: git, python3, NCBI blast
RUN apt-get update && apt-get install -y \
    gawk \
    gcc \
    git \
    libz-dev \
    locales \
    make \
    unzip \
    bzip2 \
    libbz2-dev \
    wget \
    python3 \
    python3-pip \
    ncbi-blast+
RUN ln -s /bin/python3 /bin/python

WORKDIR /opt/


# Install Clustal Omega http://www.clustal.org/omega/
RUN wget http://www.clustal.org/omega/clustalo-1.2.4-Ubuntu-x86_64 \
  && mv clustalo* clustalo \
  && chmod 777 clustalo

# Install MUSCLE
RUN wget https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.linux_intel64 \
  && mv muscle5* muscle5 \
  && chmod 777 muscle5 \
  && ln -s muscle5 muscle

#Install BioPython & pyfasta
RUN pip3 install biopython
RUN pip3 install pyfasta

#Install NCBI BLCA
RUN git clone https://github.com/qunfengdong/BLCA.git \
  && chmod 777 BLCA/1.subset_db_acc.py \
  && chmod 777 BLCA/1.subset_db_gg.py \
  && chmod 777 BLCA/2.blca_main.py

#Put things in PATH
ENV LC_ALL C
ENV PATH=/opt:/opt/BLCA:$PATH
