#Create container for BIMBAM (http://www.haplotype.org/software.html) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

#RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
#RUN dnf -y distro-sync
#RUN dnf -y makecache
#RUN dnf -y groupinstall "Development Tools"
#RUN dnf install -y gcc make git wget gsl

#WORKDIR /opt
#RUN wget http://www.haplotype.org/download/bimbam-latest.tar.gz
#tar -xvf bimbam-latest.tar.gz
#cd bimbam

#libgsl.a
#libgslcblas.a

#make
