#Create container for LongStitch (https://github.com/bcgsc/LongStitch) to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget python3

WORKDIR /opt

#Install tigmint


#install longstitch
#RUN wget https://github.com/bcgsc/LongStitch/releases/download/v1.0.3/longstitch-1.0.3.tar.gz && \
#  tar -xvf longstitch*tar.gz && \
#  rm -rf longstitch*tar.gz && \
#  mv longstitch* longstitch
  #cd longstitch* && \

#ENV PATH /opt/longstitch:$PATH
