#Create container for Maker (https://github.com/Yandell-Lab/maker) to run on NEU Discovery
#Modified from: https://github.com/chrishah/maker-docker

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

#RepeatMasker Library = default curated - Dfam

#https://github.com/chrishah/maker-docker/blob/master/ubuntu-basic/Dockerfile
RUN apt-get update --fix-missing
RUN apt-get install -y build-essential vim git wget unzip language-pack-en rsync libcurl4 zlib1g-dev libpq-dev mpich cpio

RUN apt-get install -y perl cpanminus
RUN apt-get install -y python3 python3-pip
RUN pip install h5py
RUN apt-get install -y exonerate hmmer ncbi-blast+

#Add blast executables to location expected by RepeatModeler
RUN for f in $(find /usr/bin/ -name '*blast*'); do ln -s $f /usr/local/bin/; done
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/dustmasker /usr/local/bin/dustmasker

#Set language
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
