#Create container for STRIDE (https://github.com/davidemms/STRIDE) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git python3
RUN apt-get install -y python3-numpy python3-scipy
RUN apt-get -y update
RUN apt-get -y upgrade

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y python3-ete3

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt

RUN git clone https://github.com/davidemms/STRIDE
RUN ln -s /opt/STRIDE/stride/stride.py /opt/stride
RUN chmod +x /opt/stride

ENV PATH /opt/STRIDE:$PATH
