#Create container for Assembly Stats (https://github.com/rjchallis/assembly-stats) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git
RUN apt-get install -y perl cpanminus

#Set language
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

#Install required PERL modules
RUN cpanm strict && \
        cpanm List::Util && \
        cpanm JSON

WORKDIR /opt

RUN git clone https://github.com/rjchallis/assembly-stats
RUN ln -s /opt/assembly-stats/pl/asm2stats.pl /opt/asm2stats.pl
RUN chmod +x /opt/asm2stats.pl

ENV PATH /opt:$PATH
#
#
