#Create container for DASTool (https://github.com/cmks/DAS_Tool) to run on NEU Discovery

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Jason Selwyn


RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential \
  gcc \
  ruby-full \
  git \
  make \
  wget \
  libtool \
  m4 \
  automake


ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y r-base

RUN Rscript -e "install.packages(c('data.table', 'magrittr', 'docopt'), repos='https://cran.rstudio.com')"

WORKDIR /opt/

## Install pullseq
RUN git clone https://github.com/bcthomas/pullseq.git &&\
  cd pullseq &&\
  ./bootstrap &&\
  ./configure &&\
  make &&\
  make install

## Install Prodigal
RUN git clone https://github.com/hyattpd/Prodigal &&\
  cd Prodigal &&\
  make install

## Install Diamond
RUN wget http://github.com/bbuchfink/diamond/releases/download/v2.1.9/diamond-linux64.tar.gz &&\
  tar xzf diamond-linux64.tar.gz &&\
  rm -rf diamond-linux64.tar.gz

#Put things in PATH
ENV LC_ALL C
ENV PATH=/opt:/opt/pullseq:/opt/Prodigal:$PATH
