#Create container for EnTAP https://entap.readthedocs.io/en/latest/ to run on NEU Discovery - copied from here: https://github.com/joelnitta/entap-docker/blob/main/Dockerfile
FROM python:3

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

ARG DEBIAN_FRONTEND=noninteractive

################
### apt deps ###
################

RUN apt-get update && \
# Add source for R to sources.list
  echo "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/" >> /etc/apt/sources.list && \
  apt-get install -y --no-install-recommends \
# cmake for EnTAP, R gfortran libblas-dev for RSEM->EnTAP
  cmake \
  r-base \
  gfortran \
  libblas-dev

#########################
### install miniconda ###
#########################

ENV CONDA_DIR=/miniconda3

# make non-activate conda commands available
ENV PATH=$CONDA_DIR/bin:$PATH

RUN MINICONDA_VERSION=py37_4.9.2 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-$MINICONDA_VERSION-Linux-x86_64.sh -O ~/miniconda.sh && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh

##################
### other apps ###
##################

# make dir for software installs
ENV APPS_HOME=/apps
RUN mkdir $APPS_HOME

### Diamond ###
RUN APPNAME=diamond && \
    VERSION=v2.0.7 && \
    mkdir $APPS_HOME/$APPNAME && \
    cd $APPS_HOME/$APPNAME && \
    wget https://github.com/bbuchfink/$APPNAME/releases/download/$VERSION/$APPNAME-linux64.tar.gz && \
    tar -xzf $APPNAME-linux64.tar.gz && \
    rm $APPNAME-linux64.tar.gz

ENV PATH=/apps/diamond/:$PATH

### TransDecoder ###
# use v5.3.0 as specified in EnTAP docs
RUN APPNAME=TransDecoder && \
    VERSION=v5.3.0 && \
    mkdir $APPS_HOME/$APPNAME && \
    cd $APPS_HOME/$APPNAME && \
    wget https://github.com/$APPNAME/$APPNAME/archive/$APPNAME-$VERSION.tar.gz && \
    tar -xzf $APPNAME-$VERSION.tar.gz && \
    rm $APPNAME-$VERSION.tar.gz && \
# need to install a missing perl module
    cpan App::cpanminus && \
    cpanm URI::Escape

ENV PATH=/apps/TransDecoder/TransDecoder-TransDecoder-v5.3.0/:$PATH

### RSem ###
# v1.3.3 is bundled with EnTAP v.0.10.8-beta but lacks make file
# need to manually run install.packages("blockmodeling") or will get error
# https://github.com/deweylab/RSEM/issues/162
#
RUN APPNAME=RSEM && \
    VERSION=1.3.3 && \
    mkdir $APPS_HOME/$APPNAME && \
    cd $APPS_HOME/$APPNAME && \
    wget https://github.com/deweylab/$APPNAME/archive/refs/tags/v$VERSION.tar.gz && \
    tar -xzf v$VERSION.tar.gz && \
    rm v$VERSION.tar.gz && \
    cd $APPNAME-$VERSION && \
    Rscript -e 'install.packages("blockmodeling")' \
    make && \
    make ebseq && \
    make install

### EnTAP ###
# Download EnTAP and build included deps
# https://entap.readthedocs.io/en/latest/Getting_Started/installation.html
RUN APPNAME=EnTAP && \
  VERSION=v0.10.8-beta && \
  mkdir $APPS_HOME/$APPNAME && \
  cd $APPS_HOME/$APPNAME && \
  wget https://gitlab.com/enTAP/EnTAP/-/archive/$VERSION/$APPNAME-$VERSION.tar.gz && \
  tar -xzf $APPNAME-$VERSION.tar.gz && \
  rm $APPNAME-$VERSION.tar.gz && \
  cd $APPS_HOME/$APPNAME/$APPNAME-$VERSION/ && \
  cmake CMakeLists.txt && \
  make

ENV PATH=/apps/EnTAP/EnTAP-v0.10.8-beta/:$PATH


### Create Initial ini file ###
WORKDIR /opt

## Program Locations
RUN cat /apps/EnTAP/EnTAP-v0.10.8-beta/entap_config.ini |\
  sed "s|entap-graph=/src/entap_graphing.py|entap-graph=/apps/EnTAP/EnTAP-v0.10.8-beta/src/entap_graphing.py|g" |\
  sed "s|rsem-calculate-expression=/libs/RSEM-1.3.3//rsem-calculate-expression|rsem-calculate-expression=/apps/RSEM/RSEM-1.3.3/rsem-calculate-expression|g" |\
  sed "s|rsem-sam-validator=/libs/RSEM-1.3.3//rsem-sam-validator|rsem-sam-validator=/apps/RSEM/RSEM-1.3.3/rsem-sam-validator|g" |\
  sed "s|rsem-prepare-reference=/libs/RSEM-1.3.3//rsem-prepare-reference|rsem-prepare-reference=/apps/RSEM/RSEM-1.3.3/rsem-prepare-reference|g" |\
  sed "s|convert-sam-for-rsem=/libs/RSEM-1.3.3//convert-sam-for-rsem|convert-sam-for-rsem=/apps/RSEM/RSEM-1.3.3/convert-sam-for-rsem|g" |\
  sed "s|transdecoder-long-exe=TransDecoder.LongOrfs|transdecoder-long-exe=/apps/TransDecoder/TransDecoder-TransDecoder-v5.3.0/TransDecoder.LongOrfs|g" |\
  sed "s|transdecoder-predict-exe=TransDecoder.Predict|transdecoder-predict-exe=/apps/TransDecoder/TransDecoder-TransDecoder-v5.3.0/TransDecoder.Predict|g" |\
  sed "s|diamond-exe=/libs/diamond-0.9.9/bin/diamond|diamond-exe=/apps/diamond/diamond|g" >\
  /opt/entap_config.ini
RUN mv /opt/entap_config.ini /apps/EnTAP/EnTAP-v0.10.8-beta/entap_config.ini


## Database Locations
RUN cat /apps/EnTAP/EnTAP-v0.10.8-beta/entap_config.ini |\
  sed "s|entap-db-bin=/bin/entap_database.bin|entap-db-bin=/work/vollmer/Databases/entap/entap_database.bin|g" |\
  sed "s|entap-db-sql=/databases/entap_database.db|entap-db-sql=/work/vollmer/Databases/entap/entap_database.db|g" |\
  sed "s|eggnog-sql=/databases/eggnog.db|eggnog-sql=/work/vollmer/Databases/entap/eggnog.db|g" |\
  sed "s|eggnog-dmnd=/bin/eggnog_proteins.dmnd|eggnog-dmnd=/work/vollmer/Databases/entap/eggnog_proteins.dmnd|g" |\
  /opt/entap_config.ini
RUN mv /opt/entap_config.ini /apps/EnTAP/EnTAP-v0.10.8-beta/entap_config.ini


## Settings

#complete=false
#transdecoder-m=100
#transdecoder-no-refine-starts=false
#output-format=1,3,4,5,6,
#ontology=0,
#level=0,1,
#taxon=
#qcoverage=50
#tcoverage=50
#contam=
#e-value=1e-05
#uninformative=conserved,predicted,unknown,unnamed,hypothetical,putative,unidentified,uncharacterized,uncultured,uninformative,
