#Create container for LSD2 (https://github.com/tothuhien/lsd2) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git

WORKDIR /opt

RUN git clone https://github.com/tothuhien/lsd2
RUN cp /opt/lsd2/bin/lsd2_unix /opt/lsd2/bin/lsd2

ENV PATH /opt/lsd2/bin:$PATH
