#Create container for MSMC2 (https://github.com/stschiff/msmc2) & MSMC-TOOLS (https://github.com/stschiff/msmc-tools/blob/master/msmc-tutorial/guide.md) to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget gsl-devel epel-release
RUN dnf install -y snapd
RUN systemctl enable --now snapd.socket
RUN ln -s /var/lib/snapd/snap /snap
RUN snap install dmd --classic

WORKDIR /opt


ENV PATH /opt/:$PATH
