#Create container for R to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y r-base

RUN Rscript -e "install.packages(c('tidyverse', 'tidymodels', 'BiocManager'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('future.batchtools', 'dofuture', 'magrittr'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('cmdstanr', 'rstanarm', 'tidyposterior'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('discrim', 'baguette', 'themis', 'finetune'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('remotes', 'brulee', 'bonsai', 'rules'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('patchwork', 'adegenet', 'desirability2', 'fastshap'), repos='https://cran.rstudio.com')"
RUN Rscript -e "install.packages(c('ggbump', 'ggbeeswarm', 'tidytext', 'shapviz'), repos='https://cran.rstudio.com')"


#ENV PATH /opt/lsd2/bin:$PATH
