#Create container for pita () to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
#RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make wget tar bzip2

WORKDIR /opt

#Downgrade Perl to 5.8.9 (end of 2008 version - last update to PITA)
RUN wget https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/perl-5.8.9.tar.bz2 \
  && tar -xvf perl*bz2 \
  && rm -rf perl*bz2 \
  && cd perl* \
  && sh Configure -de \
  && make \
  && make install \
  && rm -rf /usr/bin/perl \
  && ln -s /opt/perl*/perl /usr/bin/perl

WORKDIR /opt
RUN wget https://genie.weizmann.ac.il/pubs/mir07/64bit_exe_pita_prediction.tar.gz -O /opt/pita
RUN tar xvfz pita

RUN make install

RUN chmod -R 755 lib Bin pita_prediction.pl
RUN chmod 775 known_mirs

ENV PATH /opt:$PATH
