#Create container for FLO (https://github.com/wurmlab/flo) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y ruby-full wget
RUN gem install bio

WORKDIR /opt
RUN wget -c https://github.com/yeban/flo/archive/master.tar.gz -O flo.tar.gz \
  && tar xvf flo.tar.gz \
  && mv flo-master flo \
  && rm flo.tar.gz \
  && flo/scripts/install.sh

RUN mv /opt/ext/genometools* /opt/ext/genometools
RUN mv /opt/ext/parallel* /opt/ext/parallel

## Program Locations
RUN cat /opt/flo/opts_example.yaml |\
  sed "s|  - 'ext/kent/bin'|#  - 'ext/kent/bin'|g" |\
  sed "s|  - 'ext/parallel-20150722/src'|#  - 'ext/parallel-20150722/src'|g" |\
  sed "s|  - 'ext/genometools-1.5.6/bin'|#  - 'ext/parallel-20150722/src'|g" >\
  /opt/flo_config.yaml

ENV PATH /opt:/opt/ext:/opt/flo:/opt/flo/scripts:/opt/ext/parallel/src:/opt/ext/genometools/bin:/opt/ext/kent/bin::$PATH
