#Create container for redbean (wtdbg2) https://github.com/ruanjue/wtdbg2 to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git

WORKDIR /opt

RUN git clone https://github.com/ruanjue/wtdbg2

WORKDIR /opt/wtdbg2

RUN make

ENV PATH /opt/wtdbg2:$PATH
#ENV PATH /opt/wtdbg2/wtdbg2:$PATH
#ENV PATH /opt/wtdbg2/wtpoa-cns:$PATH
