#Create container for LSD2 (https://github.com/tothuhien/lsd2) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y r-base

RUN Rscript -e "install.packages(c('ape'), repos='https://cran.rstudio.com')"

#Make script to convert tree to newick
RUN echo '#!/usr/bin/env Rscript' > /opt/tree_convert
RUN echo "ape::read.tree(commandArgs(trailingOnly = TRUE)) |> ape::write.tree(file = paste0(commandArgs(trailingOnly = TRUE), '.newick'))" >> /opt/tree_convert
RUN chmod +x /opt/tree_convert

#Make script to make output ultrametric (issue with rounding)
RUN echo '#!/usr/bin/env Rscript' > /opt/tree_ultrametric
RUN echo "ape::read.nexus(commandArgs(trailingOnly = TRUE)) |> ape::chronoMPL() |> ape::write.tree(file = paste0(commandArgs(trailingOnly = TRUE), '.ultrametric'))" >> /opt/tree_ultrametric
RUN chmod +x /opt/tree_ultrametric
ENV PATH /opt:$PATH

#RUN echo '#!/usr/bin/env Rscript' > /opt/tree_ultrametric
#RUN echo "multiply_edge <- function(tree){tree\$edge.length <- tree\$edge.length * 1e6; tree}" >> /opt/tree_ultrametric
#RUN echo "ape::read.nexus(commandArgs(trailingOnly = TRUE)) |> multiply_edge() |> ape::chronoMPL() |> ape::write.tree(file = paste0(commandArgs(trailingOnly = TRUE), '.ultrametric'))" >> /opt/tree_ultrametric
#RUN chmod +x /opt/tree_ultrametric
#ENV PATH /opt:$PATH

ENV PATH /opt:$PATH

WORKDIR /opt

RUN git clone https://github.com/tothuhien/lsd2
RUN cp /opt/lsd2/bin/lsd2_unix /opt/lsd2/bin/lsd2

ENV PATH /opt/lsd2/bin:$PATH
