FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget python3 zip perl
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN dnf config-manager --set-enabled powertools


WORKDIR /opt

RUN wget http://www.city-fan.org/ftp/contrib/yum-repo/rhel8/x86_64/perl-Graphics-TIFF-6-4.el8.x86_64.rpm
RUN wget http://www.city-fan.org/ftp/contrib/yum-repo/rhel8/x86_64/perl-PDF-API2-2.033-6.el8.noarch.rpm
RUN wget http://www.city-fan.org/ftp/contrib/yum-repo/rhel8/x86_64/perl-Font-TTF-1.06-8.el8.noarch.rpm

RUN dnf -y install perl-PDF-API2-2.033-6.el8.noarch.rpm perl-Font-TTF-1.06-8.el8.noarch.rpm perl-Graphics-TIFF-6-4.el8.x86_64.rpm

RUN git clone https://github.com/rajewsky-lab/mirdeep2.git

WORKDIR /opt/mirdeep2

RUN perl install.pl
RUN /bin/bash -c "source ~/.bashrc"
RUN perl install.pl

ENV PATH /opt/mirdeep2/bin:$PATH
ENV PERL5LIB /opt/mirdeep2/lib/perl5
