#Create container for BIMBAM (http://www.haplotype.org/software.html) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y gcc make wget libgsl-dev
RUN ln /usr/lib/x86_64-linux-gnu/libgsl* /usr/local/lib

WORKDIR /opt
RUN wget http://www.haplotype.org/download/bimbam-latest.tar.gz && \
  tar -xvf bimbam-latest.tar.gz && \
  rm bimbam-latest.tar.gz && \
  cd bimbam && \
  make
  
ENV PATH /opt/bimbam:$PATH
