#Create container for LSD2 (https://github.com/tothuhien/lsd2) to run on NEU Discovery

FROM ubuntu

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y git

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y r-base

RUN Rscript -e "install.packages(c('ape'), repos='https://cran.rstudio.com')"

#Make script to convert tree to newick
echo '#!/usr/bin/env Rscript' > /opt/tree_convert
echo "ape::read.tree(commandArgs(trailingOnly = TRUE)) |> ape::write.tree(file = paste0(commandArgs(trailingOnly = TRUE), '.newick'))" >> /opt/tree_convert
chmod +x /opt/tree_convert
ENV PATH /opt

WORKDIR /opt

RUN git clone https://github.com/tothuhien/lsd2
RUN cp /opt/lsd2/bin/lsd2_unix /opt/lsd2/bin/lsd2

ENV PATH /opt/lsd2/bin:$PATH
