#Create container for Kmergenie (http://kmergenie.bx.psu.edu/)to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y gcc make git wget python3
RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled powertools
RUN dnf install -y R
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt

RUN wget http://kmergenie.bx.psu.edu/kmergenie-1.7051.tar.gz
RUN tar xzf kmergenie-1.7051.tar.gz
RUN rm -rf kmergenie-1.7051.tar.gz

WORKDIR /opt/kmergenie-1.7051

RUN make

ENV PATH /opt/kmergenie-1.7051.tar.gz:$PATH
