#Create container for DASTool (https://github.com/cmks/DAS_Tool) to run on NEU Discovery

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Jason Selwyn

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential \
  gcc \
  git
