#Create container for MinIONQC https://github.com/roblanf/minion_qc to run on NEU Discovery

FROM centos

MAINTAINER Jason Selwyn "j.selwyn@northeastern.edu"

RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y makecache

RUN dnf -y groupinstall "Development Tools"
RUN dnf config-manager --set-enabled powertools
RUN dnf -y install wget epel-release
RUN dnf -y install R

WORKDIR /opt

RUN wget https://raw.githubusercontent.com/roblanf/minion_qc/master/MinIONQC.R -O ./MinIONQC.R

RUN Rscript -e 'install.packages(c("data.table", "futile.logger", "ggplot2", "optparse", "plyr", "readr", "reshape2", "scales", "viridis", "yaml"), repos="http://cran.us.r-project.org")'

RUN sed '2 a options(bitmapType="cairo")' MinIONQC.R > MinIONQC.R
RUN chmod ugo+x MinIONQC.R
ENV PATH /opt:$PATH
